version: "3.9"

services:
  frontend:
    build:
      context: ./nowl_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./nowl_frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./nowl_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./nowl_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload